version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estoque
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      # A linha foi movida para cá, no serviço 'db'
      - ./backend/database:/docker-entrypoint-initdb.d

  api:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8000:80"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - api